### PR TITLE
Plugs a few of the issues uncovered by Coverity

### LINKED ISSUE #403: pppoe on master after commit ba7f7e053d is said to be broken
[This change ](https://github.com/ppp-project/ppp/commit/ba7f7e053daae846a54a1d08d3d133a5f1266ace) is said to break pppoe connections (see comments at the bottom by @wongsyrone)

I am filing this issue to track it here as an issue vs. in a comment on a change. Hope @wongsyrone is able to provide details here to help resolve the issue she was having. 

Also, @jkroonza I believe pppoe was working for both of us when the change was comitted.

### PR DESCRIPTION
**Pull request by enaess**
Should address a few of the Coverity issues found in #394 
Also closes #403

### CODE REVIEW

**Comment by enaess** [comment]
Also closes #403

File: pppd/plugins/pppoatm/pppoatm.c [hunk 1]
```diff
@@ -92,7 +92,7 @@ static int setdevname_pppoatm(const char *cp, const char **argv, int doit)
 		return 1;
 
 	memcpy(&pvcaddr, &addr, sizeof pvcaddr);
-	strlcpy(devnam, cp, MAXPATHLEN);
+	strlcpy(devnam, cp, sizeof(devname));
```
Comment (paulusmack) [inline pppd/plugins/pppoatm/pppoatm.c]: devname not devnam??

Comment (enaess) [reply pppd/plugins/pppoatm/pppoatm.c]: You are looking at an outdated version of the file, current PR has the change you suggested "devnam"
